apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../../docker-compose.yml convert
    kompose.version: 1.21.0 ()
  labels:
    io.kompose.service: productcli
  name: productcli
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: productcli
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../../docker-compose.yml convert
        kompose.version: 1.21.0 ()
      labels:
        io.kompose.service: productcli
    spec:
      containers:
      - command:
        - CompileDaemon
        - --build=go build -o productClient ./product/client/
        - --command=./productClient
        env:
        - name: MICRO_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: MICRO_SERVER_ADDRESS
              name: product-docker-compose-cli-env
        image: productcli
        imagePullPolicy: ""
        name: productclicont
        ports:
        - containerPort: 50051
        resources: {}
#        volumeMounts:
#        - mountPath: /go/src/cdcon21builddriver/product/client
#          name: productcli-claim0
      restartPolicy: Always
      serviceAccountName: ""
#      volumes:
#      - name: productcli-claim0
#        persistentVolumeClaim:
#          claimName: productcli-claim0
