apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../../docker-compose.yml convert
    kompose.version: 1.21.0 ()
  labels:
    io.kompose.service: promotioncli
  name: promotioncli
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: promotioncli
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../../docker-compose.yml convert
        kompose.version: 1.21.0 ()
      labels:
        io.kompose.service: promotioncli
    spec:
      containers:
      - command:
        - CompileDaemon
        - --build=go build -o promotionClient ./promotion/client/
        - --command=./promotionClient
        env:
        - name: MICRO_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: MICRO_SERVER_ADDRESS
              name: promotion-docker-compose-cli-env
        image: promotioncli
        imagePullPolicy: ""
        name: promotionclicont
        ports:
        - containerPort: 50051
        resources: {}
#        volumeMounts:
#        - mountPath: /go/src/cdcon21builddriver/promotion/client
#          name: promotioncli-claim0
      restartPolicy: Always
      serviceAccountName: ""
#      volumes:
#      - name: promotioncli-claim0
#        persistentVolumeClaim:
#          claimName: promotioncli-claim0
