---
# Shared definition block
# This is where you would define any attributes that all your jobs will
# inherit.
shared:
  # annotations to control amount of cpu and ram used
  annotations:
    screwdriver.cd/cpu: MICRO
    screwdriver.cd/ram: MICRO

# Jobs definition block
jobs:
  main:
    image: docker
#    requires: [useTemplate]
    annotations:
      # Enable docker in docker to allow image building
      screwdriver.cd/dockerEnabled: true
    # enable secrets used in this pipeline
    secrets:
      - DOCKER_LOGIN_NAME
      - DOCKER_LOGIN_PWD
    steps:
      - secretValue: echo $DOCKER_LOGIN_NAME
      # access to the docker is using this address
      - dockerHost: echo $DOCKER_HOST
      - dockerCheck: docker version
      - buildImg: docker build -t bolbeck/cdconweb -f  ./web/Dockerfile ./web
      - dockerlogin: docker login -u $DOCKER_LOGIN_NAME -p $DOCKER_LOGIN_PWD
      - publish: docker push bolbeck/cdconweb
