---
# Attributes that all the jobs  inherit.
shared:
  # Common env vars
  environment:
    GOPATH: /sd/workspace
    GO111MODULE: on

  # annotations to control amount of cpu and ram used
#  annotations:
#    screwdriver.cd/cpu: MICRO
#    screwdriver.cd/ram: MICRO

# Event cache shares data between jobs
cache:
  pipeline: [/sd/workspace/pkg/mod]

# Jobs definition block
jobs:
  main:
    image: golang
    # Check if runs required on each pr or commit
    requires: [~pr, ~commit]
    # Only run job if change affected one of the folders below
    sourcePaths:
      - "promotion/server/"
      - "globalerrors/"
      - "globalMonitoring"
      - "globalProtos"
      - "globalUtils/"
    steps:
      # Check if the cache dir exists
      - checkCacheDir: ls /sd/workspace
      # This step downloads and installs packages and dependencies
      - download: go mod download
      - cd: cd promotion/server
      #  Validate code
#      - vet: go  vet .
      # Format code
      - gofmt: "find . -name '*.go' | xargs gofmt -s -w"
      #  Run tests
      #- test: go test .
      #  Compile binary
      - build: go build -o promotionsrv .
  useTemplate:
    requires:
      - main
    # Use the steps from this template
    template: bolbeck/goinit@1.0.1
    steps:
      # steps that will run before/after certain template steps
      - predownload: ls /sd/workspace/pkg/mod
      - pregofmt: cd promotion/server
      - posttest: go build -o promotionsrv .
#  webImage:
#    image: docker
#    #    requires: [useTemplate]
#    requires: [useTemplate]
#    #    sourcePaths: ["web/sapper/"]
#    annotations:
#      # Enable docker in docker to allow image building
#      screwdriver.cd/dockerEnabled: true
#    # enable secrets used in this pipeline
#    secrets:
#      - DOCKER_LOGIN_NAME
#      - DOCKER_LOGIN_PWD
#    steps:
#      - secretValue: echo $DOCKER_LOGIN_NAME
#      # access to the docker is using this address
#      - dockerHost: echo $DOCKER_HOST
#      - dockerCheck: docker version
#      - buildImg: docker build -t bolbeck/cdconweb -f  ./web/Dockerfile ./web
#      - dockerlogin: docker login -u $DOCKER_LOGIN_NAME -p $DOCKER_LOGIN_PWD
#      - publish: docker push bolbeck/cdconweb