---
# Shared definition block
# This is where you would define any attributes that all your jobs will
# inherit.
shared:
  # A map of environment variables that we want to set
  environment:
    APIURL: 'http://localhost:8080/'
  # annotations to control amount of cpu and ram used
  annotations:
    screwdriver.cd/cpu: micro
    screwdriver.cd/ram: micro
# Parameters that can be used in steps, the values provided are defaults
# and can be overridden in the gui at build time
parameters:
  param1:
    value: "Param1 Rocks"

# Jobs definition block
jobs:
  main:
    annotations:
      screwdriver.cd/dockerEnabled: false
    image: node
    requires:
      - ~pr
      - ~commit
    steps:
     - changedir: cd web/sapper
     - npminstall: npm install
     - checkEnv: echo $APIURL
     - buildapp: npm run build
     - test: npm run test
  buildImage:
    image: docker
    annotations:
      screwdriver.cd/dockerEnabled: true
    requires:
      - main
    steps:
      - parmValue: 'echo "Param1 $(meta get parameters.param1.value)"'
      - secretValue: echo $TEST_SECRET
      - dockerHost: echo $DOCKER_HOST
      - dockerCheck: docker version
      - changedir: cd web
#      - buildImg: docker build -t cdconweb .
    # enable secrets used in this pipeline
    secrets:
      - TEST_SECRET
#  parallel:
#    image: node
#    requires:
#      - ~pr
#      - ~commit
#    steps:
#      - ls: echo $(ls)