apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../../docker-compose.yml convert
    kompose.version: 1.21.0 ()
  labels:
    io.kompose.service: usersrv
  name: usersrv
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: usersrv
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../../docker-compose.yml convert
        kompose.version: 1.21.0 ()
      labels:
        io.kompose.service: usersrv
    spec:
      containers:
        - env:
            - name: DISABLE_AUDIT_RECORDS
              valueFrom:
                configMapKeyRef:
                  key: DISABLE_AUDIT_RECORDS
                  name: user-docker-compose-env
            - name: MICRO_BROKER
              valueFrom:
                configMapKeyRef:
                  key: MICRO_BROKER
                  name: user-docker-compose-env
#            - name: MICRO_BROKER_ADDRESS
#              valueFrom:
#                secretKeyRef:
#                  key: MICRO_BROKER_ADDRESS
#                  name: usersrv-secret
            - name: MICRO_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  key: MICRO_SERVER_ADDRESS
                  name: user-docker-compose-env
#            - name: POSTGRES_CONNECT
#              valueFrom:
#                secretKeyRef:
#                  key: POSTGRES_CONNECT
#                  name: usersrv-secret
          image: bolbeck/gotemp_usersrv
          imagePullPolicy: ""
          name: usersrvcont
          ports:
            - containerPort: 50053
          resources: {}
      restartPolicy: Always
      serviceAccountName: ""
