spec:
  template:
    metadata:
      annotations:
#          postgresql://{{ .Data.data.username }}:{{ .Data.data.password }}@{{ .Data.data.server }}/{{ .Data.data.dbname }}?application_name={{ .Data.data.application_name }}
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "gotemp-usersrv"
        vault.hashicorp.com/agent-inject-secret-gotemp-database-postgresql-user.txt: "gotempkv/data/database/postgresql/user"
        vault.hashicorp.com/agent-inject-template-gotemp-database-postgresql-user.txt: |
          {{- with secret "gotempkv/data/database/postgresql/user" -}}
          export POSTGRES_CONNECT="postgresql://{{ .Data.data.username }}:{{ .Data.data.password }}@{{ .Data.data.server }}/{{ .Data.data.dbname }}?application_name={{ .Data.data.application_name }}"
          {{- end -}}
    spec:
      serviceAccountName: gotemp-usersrv
      containers:
      - name: usersrvcont
        command: ['sh', '-c', 'source /vault/secrets/gotemp-database-postgresql-user.txt && ./userServerAlp' ]
