apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../../docker-compose.yml convert
    kompose.version: 1.21.0 ()
  labels:
    io.kompose.service: microapi
  name: microapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: microapi
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../../docker-compose.yml convert
        kompose.version: 1.21.0 ()
      labels:
        io.kompose.service: microapi
    spec:
      containers:
      - args:
        - api
        - --handler=rpc
        - --namespace=cdcon21builddriver.api
        env:
        - name: MICRO_PROFILE
          value: kubernetes
#        - name: MICRO_PROXY
#          value: "network.micro.svc.cluster.local:8443"
        - name: MICRO_SERVER_IMAGE
          value: "micro/micro:v2.9.3"
        image: micro/micro:v2.9.3
        imagePullPolicy: ""
        name: microcont
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
#      volumes: null
