apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../../docker-compose.yml convert
    kompose.version: 1.21.0 ()
  labels:
    io.kompose.service: auditsrv
  name: auditsrv
spec:
  ports:
  - name: "50055"
    port: 50055
    targetPort: 50055
  - name: "2112"
    port: 2112
    targetPort: 2112
  selector:
    io.kompose.service: auditsrv
