apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../../docker-compose.yml convert
    kompose.version: 1.21.0 ()
  labels:
    io.kompose.service: auditsrv
  name: auditsrv
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auditsrv
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../../docker-compose.yml convert
        kompose.version: 1.21.0 ()
      labels:
        io.kompose.service: auditsrv
    spec:
      containers:
      - env:
        - name: DB_CONNECT
          valueFrom:
            secretKeyRef:
              key: DB_CONNECT
              name: auditsrv-secret
        - name: MICRO_BROKER
          valueFrom:
            configMapKeyRef:
              key: MICRO_BROKER
              name: audit-docker-compose-env
        - name: MICRO_BROKER_ADDRESS
          valueFrom:
            secretKeyRef:
              key: MICRO_BROKER_ADDRESS
              name: auditsrv-secret
        - name: MICRO_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: MICRO_SERVER_ADDRESS
              name: audit-docker-compose-env
        image: bolbeck/gotemp_auditsrv
        imagePullPolicy: ""
        name: auditsrvcont
        ports:
        - containerPort: 50055
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
