apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../../docker-compose.yml convert
    kompose.version: 1.21.0 ()
  labels:
    io.kompose.service: productsrv
  name: productsrv
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: productsrv
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f ../../docker-compose.yml convert
        kompose.version: 1.21.0 ()
      labels:
        io.kompose.service: productsrv
    spec:
      containers:
      - env:
        - name: DB_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: DB_ADDRESS
              name: product-docker-compose-env
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              key: DB_PASS
              name: productsrv-secret
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              key: DB_USER
              name: product-docker-compose-env
        - name: DISABLE_AUDIT_RECORDS
          valueFrom:
            configMapKeyRef:
              key: DISABLE_AUDIT_RECORDS
              name: product-docker-compose-env
        - name: MICRO_BROKER
          valueFrom:
            configMapKeyRef:
              key: MICRO_BROKER
              name: product-docker-compose-env
        - name: MICRO_BROKER_ADDRESS
          valueFrom:
            secretKeyRef:
              key: MICRO_BROKER_ADDRESS
              name: productsrv-secret
        - name: MICRO_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              key: MICRO_SERVER_ADDRESS
              name: product-docker-compose-env
        image: bolbeck/gotemp_productsrv
        imagePullPolicy: ""
        name: productsrvcont
        ports:
        - containerPort: 50059
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""