apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../../docker-compose.yml convert
    kompose.version: 1.21.0 ()
  labels:
    io.kompose.service: productsrv
  name: productsrv
spec:
  ports:
  - name: "50059"
    port: 50059
    targetPort: 50059
  - name: "2112"
    port: 2112
    targetPort: 2112
  selector:
    io.kompose.service: productsrv
