apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../../docker-compose.yml convert
    kompose.version: 1.21.0 ()
  labels:
    io.kompose.service: promotionsrv
  name: promotionsrv
spec:
  ports:
  - name: "50051"
    port: 50051
    targetPort: 50051
  - name: "2112"
    port: 2112
    targetPort: 2112
  selector:
    io.kompose.service: promotionsrv
