apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../../docker-compose.yml convert
    kompose.version: 1.21.0 ()
  labels:
    io.kompose.service: usersrv
  name: usersrv
spec:
  ports:
  - name: "50053"
    port: 50053
    targetPort: 50053
  - name: "2112"
    port: 2112
    targetPort: 2112
  selector:
    io.kompose.service: usersrv
